stages:
  - build

before_script:
  - mkdir -p $CI_PROJECT_DIR/install
  - git clone git@gitlab.com:NWChemEx-Project/TAMM.git 
  - git clone https://github.com/CMakePP/CMakePackagingProject.git
  - git clone git@gitlab.com:NWChemEx-Project/CMakeBuild.git 

variables:
  CMAKE_OPTIONS: "-DCMAKE_PREFIX_PATH=$CI_PROJECT_DIR/install -DCMAKE_INSTALL_PREFIX=$CI_PROJECT_DIR/install -DCMAKE_C_COMPILER=gcc -DCMAKE_CXX_COMPILER=g++ -DCPP_GITHUB_TOKEN=a942e188f9c4a0d80d069b826fdb1a3e85f3fe02"
  NUM_CORES: "20"
  CMAKE_BUILD_PARALLEL_LEVEL: "24"

default_build:
    tags:
      - linux,kamban
    stage: build
    script:
    - module load gcc-9.1.0-gcc-7.4.0-jjv2tsg mpich-3.3-gcc-9.1.0-ennj3ix cmake-3.14.2-gcc-9.1.0-jzu7ays
    - cd $CI_PROJECT_DIR/CMakeBuild
    - cmake $CMAKE_OPTIONS -DBUILD_TESTS=OFF -H. -Bbuild
    - cd build
    - make install
    - cd $CI_PROJECT_DIR/TAMM
    - cmake $CMAKE_OPTIONS -DBUILD_TESTS=OFF -DARMCI_NETWORK=MPI-TS -H. -Bbuild
    - cd build
    - make -j$NUM_CORES
    - make install
    - cd $CI_PROJECT_DIR/CMakePackagingProject
    - cmake $CMAKE_OPTIONS -DBUILD_TESTS=OFF -H. -Bbuild
    - cd build
    - make install
    - cd $CI_PROJECT_DIR
    - cmake $CMAKE_OPTIONS -DBUILD_TESTS=ON -H. -Bbuild
    - cd build
    - make -j$NUM_CORES
    - ctest -VV
